const DARAJA_BASE_URL = "https://sandbox.safaricom.co.ke"; // switch to api.safaricom.co.ke for production

const CONSUMER_KEY = process.env.DARAJA_CONSUMER_KEY;
const CONSUMER_SECRET = process.env.DARAJA_CONSUMER_SECRET;
const SHORTCODE = process.env.DARAJA_SHORTCODE;
const PASSKEY = process.env.DARAJA_PASSKEY;

// ─── OAuth access token ──────────────────────────────────────────────────────
// Daraja requires a short-lived OAuth token (valid ~1 hour) on every request.
// Generated by Basic-Auth-ing consumer key:secret against Daraja's own OAuth
// endpoint — this is Safaricom's own auth layer, separate from anything
// Telegram or Paystack related. We fetch a fresh token per STK push rather
// than caching it, since STK pushes aren't frequent enough in this bot to
// justify the complexity of a token cache with expiry tracking.
async function getAccessToken() {
  const credentials = Buffer.from(`${CONSUMER_KEY}:${CONSUMER_SECRET}`).toString("base64");

  const response = await fetch(`${DARAJA_BASE_URL}/oauth/v1/generate?grant_type=client_credentials`, {
    method: "GET",
    headers: {
      Authorization: `Basic ${credentials}`,
    },
  });

  const data = await response.json();

  if (!data.access_token) {
    throw new Error("Failed to get Daraja access token: " + JSON.stringify(data));
  }

  return data.access_token;
}

// ─── Timestamp + Password ────────────────────────────────────────────────────
// Daraja requires a specific timestamp format (YYYYMMDDHHmmss) and a
// Password field that's base64(Shortcode + Passkey + Timestamp) — this
// proves to Safaricom that the request genuinely has your shortcode's
// passkey, without sending the passkey itself in plain text on every call.
function generateTimestamp() {
  const now = new Date();
  const pad = (n) => String(n).padStart(2, "0");
  return (
    now.getFullYear().toString() +
    pad(now.getMonth() + 1) +
    pad(now.getDate()) +
    pad(now.getHours()) +
    pad(now.getMinutes()) +
    pad(now.getSeconds())
  );
}

function generatePassword(timestamp) {
  return Buffer.from(`${SHORTCODE}${PASSKEY}${timestamp}`).toString("base64");
}

// ─── STK Push (Lipa na M-Pesa Online) ───────────────────────────────────────
// This is what actually triggers the real-time prompt on the user's phone.
// callbackUrl must be a public HTTPS URL (your ngrok URL + the Daraja
// callback route) — Safaricom calls THIS URL when the user approves or
// cancels/times out, similar in spirit to Paystack's webhook but with a
// different payload shape.
//
// CheckoutRequestID (returned here) is what we save against our pending
// contribution row, so the callback can later match the result back to the
// right one.
async function initiateSTKPush({ phone, amount, accountReference, callbackUrl }) {
  const accessToken = await getAccessToken();
  const timestamp = generateTimestamp();
  const password = generatePassword(timestamp);

  const response = await fetch(`${DARAJA_BASE_URL}/mpesa/stkpush/v1/processrequest`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      BusinessShortCode: SHORTCODE,
      Password: password,
      Timestamp: timestamp,
      TransactionType: "CustomerPayBillOnline",
      Amount: amount,
      PartyA: phone, // the paying customer's number, format 2547XXXXXXXX
      PartyB: SHORTCODE,
      PhoneNumber: phone,
      CallBackURL: callbackUrl,
      AccountReference: accountReference, // shows up in the STK prompt / statement
      TransactionDesc: "Chama contribution",
    }),
  });

  const data = await response.json();

  if (data.ResponseCode !== "0") {
    throw new Error(data.errorMessage || data.ResponseDescription || "STK push failed");
  }

  return {
    checkoutRequestId: data.CheckoutRequestID,
    merchantRequestId: data.MerchantRequestID,
  };
}

module.exports = { initiateSTKPush };